CREATE SCHEMA IF NOT EXISTS "50lan_new";

CREATE TABLE IF NOT EXISTS "50lan_new"."orders_parquet" (
    "id" varchar,
    "sequence" varchar,
    "items_count" integer,
    "total" real,
    "change" real,
    "tax_subtotal" real,
    "surcharge_subtotal" real,
    "discount_subtotal" real,
    "payment_subtotal" real,
    "rounding_prices" varchar,
    "precision_prices" varchar,
    "rounding_taxes" varchar,
    "precision_taxes" varchar,
    "status" integer,
    "service_clerk" varchar,
    "service_clerk_displayname" varchar,
    "proceeds_clerk" varchar,
    "proceeds_clerk_displayname" varchar,
    "member" varchar,
    "member_displayname" varchar,
    "member_email" varchar,
    "member_cellphone" varchar,
    "invoice_type" varchar,
    "invoice_title" varchar,
    "invoice_no" varchar,
    "invoice_count" integer,
    "destination" varchar,
    "table_no" integer,
    "check_no" integer,
    "no_of_customers" integer,
    "terminal_no" varchar,
    "transaction_created" timestamp(3) without time zone,
    "transaction_submitted" timestamp(3) without time zone,
    "created" timestamp(3) without time zone,
    "modified" timestamp(3) without time zone,
    "included_tax_subtotal" real,
    "item_subtotal" real,
    "sale_period" date,
    "shift_number" integer,
    "branch_id" varchar,
    "branch" varchar,
    "transaction_voided" timestamp(3) without time zone,
    "promotion_subtotal" real,
    "void_clerk" varchar,
    "void_clerk_displayname" varchar,
    "void_sale_period" varchar,
    "void_shift_number" integer,
    "revalue_subtotal" real,
    "qty_subtotal" integer,
    "inherited_order_id" varchar,
    "inherited_desc" varchar,
    "item_surcharge_subtotal" real,
    "trans_surcharge_subtotal" real,
    "item_discount_subtotal" real,
    "trans_discount_subtotal" real,
    "service_charge_subtotal" real,
    "included_service_charge_subtotal" real,
    "s_day" varchar,
    "s_month" varchar,
    "s_year" varchar,
    "s_hour" varchar,
    "tr_date" date,
    "t_open_date" date
);